#!/bin/bash
# ============================================================================
# nas-apply.sh — Applies NAS device config from the database.
#
# This is the ONLY command www-data is permitted to run as root (via sudoers).
# It reads the nas_devices table, regenerates the FreeRADIUS clients file,
# updates UFW rules, and reloads FreeRADIUS. It takes NO user arguments —
# everything comes from the database — so there's no injection surface from
# the web form. All values are re-validated here before use.
#
# MikroTik handling (v-mikrotik):
#   * MikroTik NASes are syslog-only (no RADIUS) -> excluded from the
#     FreeRADIUS clients file.
#   * Their firewall rule uses each NAS's own syslog_port (default 514) and
#     does NOT open 1813 (no RADIUS accounting).
# ============================================================================

set -euo pipefail

APP_DIR="/opt/ipdr"
CLIENTS_FILE="/etc/freeradius/3.0/clients.d/elb-nas.conf"
CLIENTS_DIR="/etc/freeradius/3.0/clients.d"
LOG="/var/log/ipdr/nas-apply.log"

log() { echo "$(date '+%Y-%m-%d %H:%M:%S') $*" >> "$LOG"; }

DB_PASS=$(grep '^DATABASE_URL' "${APP_DIR}/.env" | sed 's/.*password=//')

run_sql() {
    PGPASSWORD="$DB_PASS" psql -h 127.0.0.1 -U ipdr_user -d ipdr -t -A -F'|' -c "$1"
}

valid_ip() {
    local ip="$1"
    [[ "$ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || return 1
    local IFS='.'; read -ra oct <<< "$ip"
    for o in "${oct[@]}"; do (( o <= 255 )) || return 1; done
    return 0
}

valid_port() {
    local p="$1"
    [[ "$p" =~ ^[0-9]+$ ]] && (( p >= 1 && p <= 65535 ))
}

log "=== NAS apply started ==="

mkdir -p "$CLIENTS_DIR"
if ! grep -q 'clients.d' /etc/freeradius/3.0/radiusd.conf 2>/dev/null; then
    if ! grep -q '\$INCLUDE clients.d/' /etc/freeradius/3.0/clients.conf 2>/dev/null; then
        echo '$INCLUDE clients.d/' >> /etc/freeradius/3.0/clients.conf
        log "Added clients.d/ include to clients.conf"
    fi
fi

# --- 2. Regenerate FreeRADIUS clients from active+enabled NON-MikroTik rows ---
TMP=$(mktemp)
echo "# Auto-generated by nas-apply.sh — DO NOT EDIT BY HAND" > "$TMP"
echo "# Managed via IPDR Settings → NAS Devices" >> "$TMP"
echo "" >> "$TMP"

# NOTE: MikroTik excluded here (syslog-only, no RADIUS client needed).
ROWS=$(run_sql "SELECT ip_address, secret, name, nas_type FROM nas_devices WHERE enabled = TRUE AND status IN ('staged','active') AND nas_type <> 'mikrotik' ORDER BY id;")

COUNT=0
while IFS='|' read -r ip secret name nastype; do
    [ -z "$ip" ] && continue
    if ! valid_ip "$ip"; then log "SKIP invalid IP: $ip"; continue; fi
    shortname=$(echo "$name" | tr -cd 'A-Za-z0-9_-' | cut -c1-32)
    [ -z "$shortname" ] && shortname="nas${COUNT}"
    nastype=$(echo "$nastype" | tr -cd 'A-Za-z0-9_-')
    [ -z "$nastype" ] && nastype="other"
    cat >> "$TMP" << EOF
client ${shortname} {
    ipaddr    = ${ip}
    secret    = "${secret}"
    shortname = ${shortname}
    nas_type  = ${nastype}
}

EOF
    COUNT=$((COUNT+1))
done <<< "$ROWS"

cp "$TMP" "$CLIENTS_FILE"
rm -f "$TMP"
chmod 640 "$CLIENTS_FILE"
chown freerad:freerad "$CLIENTS_FILE" 2>/dev/null || true
log "Wrote $COUNT RADIUS client(s) to $CLIENTS_FILE (MikroTik excluded)"

# --- 4. Validate FreeRADIUS config before reload ---
if ! freeradius -CX >/dev/null 2>&1; then
    log "ERROR: FreeRADIUS config validation failed — NOT reloading"
    echo "CONFIG_INVALID"
    exit 3
fi

# --- 5. UFW rules for ALL active+enabled NASes (both vendors) ---
# Non-MikroTik: 514/udp syslog + 1813/udp radius acct (original behaviour).
# MikroTik: its own syslog_port, no 1813.
ACTIVE=$(run_sql "SELECT ip_address, nas_type, COALESCE(source_ip, ip_address), COALESCE(syslog_port, 514) FROM nas_devices WHERE enabled = TRUE AND status IN ('staged','active') ORDER BY id;")
MT_COUNT=0
OTHER_COUNT=0
while IFS='|' read -r ip nastype srcip sport; do
    [ -z "$ip" ] && continue
    # For MikroTik, logs arrive from source_ip; open that. For others, the NAS ip.
    fwip="$ip"
    if [ "$nastype" = "mikrotik" ]; then
        fwip="$srcip"
        valid_ip "$fwip" || { log "SKIP mikrotik bad src: $fwip"; continue; }
        valid_port "$sport" || sport=514
        ufw allow from "$fwip" to any port "$sport" proto udp >/dev/null 2>&1 || true
        MT_COUNT=$((MT_COUNT+1))
    else
        valid_ip "$fwip" || continue
        ufw allow from "$fwip" to any port 514 proto udp >/dev/null 2>&1 || true
        ufw allow from "$fwip" to any port 1813 proto udp >/dev/null 2>&1 || true
        OTHER_COUNT=$((OTHER_COUNT+1))
    fi
done <<< "$ACTIVE"
log "UFW ensured: $OTHER_COUNT non-mikrotik, $MT_COUNT mikrotik"

# --- 6. Reload FreeRADIUS ---
systemctl reload freeradius 2>/dev/null || systemctl restart freeradius
log "FreeRADIUS reloaded"

# --- 7. Mark staged rows active ---
run_sql "UPDATE nas_devices SET status='active', applied_at=NOW() WHERE status='staged' AND enabled=TRUE;" >/dev/null

# --- 8. Remove UFW rules for disabled devices (both vendors), then purge removing ---
DISABLED=$(run_sql "SELECT ip_address, nas_type, COALESCE(source_ip, ip_address), COALESCE(syslog_port, 514) FROM nas_devices WHERE enabled = FALSE;")
while IFS='|' read -r dip nastype srcip sport; do
    [ -z "$dip" ] && continue
    if [ "$nastype" = "mikrotik" ]; then
        valid_ip "$srcip" || continue
        valid_port "$sport" || sport=514
        ufw delete allow from "$srcip" to any port "$sport" proto udp >/dev/null 2>&1 || true
    else
        valid_ip "$dip" || continue
        ufw delete allow from "$dip" to any port 514 proto udp >/dev/null 2>&1 || true
        ufw delete allow from "$dip" to any port 1813 proto udp >/dev/null 2>&1 || true
    fi
done <<< "$DISABLED"

run_sql "DELETE FROM nas_devices WHERE status = 'removing';" >/dev/null

log "=== NAS apply complete: $COUNT RADIUS client(s), MikroTik firewall handled ==="
echo "OK:$COUNT"
